### ISSUE TITLE
Error: Expected lua number

### ISSUE THREAD

**Issue by SystematicError** [edluffy/origami.nvim#11]
Hey, I recently decided to try out this plugin and noticed that when running the following command`:lua require("hologram").add_image(0, "/tmp/test.png", 5, 5)` I get this error:

```
E5108: Error executing lua ...e/pack/packer/start/hologram.nvim/lua/hologram/image.lua:20: Expected lua number                                                                              
stack traceback:                                                                                                                                                                            
        [C]: in function 'nvim_buf_set_extmark'                                                                                                                                             
        ...e/pack/packer/start/hologram.nvim/lua/hologram/image.lua:20: in function 'new'                                                                                                   
        ...te/pack/packer/start/hologram.nvim/lua/hologram/init.lua:120: in function 'add_image'                                                                                            
        [string ":lua"]:1: in main chunk     
```

After scouring the code, I  noticed something in this snippet:

```lua
function Image:new(opts)
    opts = opts or {}

    local cur_row, cur_col = unpack(vim.api.nvim_win_get_cursor(0))
    opts.row = opts.row or cur_row
    opts.col = opts.col or cur_col

    local buf = vim.api.nvim_get_current_buf()
    local ext = vim.api.nvim_buf_set_extmark(buf, vim.g.hologram_extmark_ns, opts.row, opts.col, {})

    local obj = setmetatable({
        id = buf*100 + ext,
        source = opts.source
    }, self)

    obj:identify()

    return obj
end
```

Here, no fallback value is set for `vim.g.hologram_extmark_ns`, so if the user hasn't defined it, it returns `nil`, which the nvim api does not like. I'm not really sure what extmark_ns really does so I'm not submitting a pull request, but hopefully this issue should be easy to fix :)

Nvim version info:
```
NVIM v0.6.1
Build type: Release
LuaJIT 2.0.5
Features: +acl +iconv +tui
```

**Comment by Cassin01** [comment]
I think your configuration didn't call  ``require'hologram'.setup()`` before hand, so if you are packer user , can you try to use the code below (and :PackerComple).

```lua
  use {'edluffy/hologram.nvim',
      config = function()
          require'hologram'.setup {}
          local function map(input, output)
              vim.api.nvim_set_keymap('n', input, output, { noremap = true, silent = false})
          end
          function Fft()
              local my_image = require('hologram.image'):new({ source="/Users/.../something.png", row=2,col=5})
              my_image:transmit()    
          end
          map('<space>lf', ":lua Fft()<cr>")
      end,
  }
```

If you get `line value outside range` error, fill the file with space.

**Comment by SystematicError** [comment]
Thanks for the help! Adding the setup function fixes it. Initially didn't have it due to it not being mentioned in the README

**Comment by winkee01** [comment]
@Cassin01 I got the error `line value outside range`, what does it mean? what do you mean by `fill the file with space`???

**Comment by edluffy** [comment]
@winkee01 The row for an image has to be a valid line inside the buffer in which it is placed (with 0 based indices).  I probably didn't make that clear enough in the docs. I have a lot of changes planned for this plugin so this issue and a few others should be fixed soon.

**Comment by winkee01** [comment]
Sorry, still didn't quite understand. my settings is your minimal
```
local my_image = require('hologram.image'):new({
        source = '/Users/.../Documents/Chun-Li.jpeg',
        row = 11,
        col = 0,
    })
```

And I opened a file with 200+ lines, which is obviously more than 11 rows. But I still get this error.

**Comment by winkee01** [comment]
Sorry, still didn't quite understand. my settings is your minimal
```
local my_image = require('hologram.image'):new({
        source = '/Users/./Documents/Chun-Li.jpeg',
        row = 11,
        col = 0,
    })
```


I opened a file

**Comment by Cassin01** [comment]
The buffer must be filled with aviturarry words
Can you fill the file that you want to show the picture on with any 11 words.

l

**Comment by Cassin01** [comment]
The buffer must be filled with any words till the row you defined (11 at that time).
Can you fill the file that you want to show the picture on with any 11 words?

**Comment by winkee01** [comment]
I filled my file with 100 x 100 spaces, still not able to display the image. Do you mean I have to fill it with printable characters?

Ok, this time, I fill the file with characters, but still can't display the image.

**Comment by edluffy** [comment]
Only PNG file format is supported right now so that is probably why

**Comment by Cassin01** [comment]
> you mean I have to fill it with printable characters?

No
> I filled my file with 100 x 100 spaces, still not able to display the image. 

My solution may not work or there is another problem on your environment.

**Comment by winkee01** [comment]
I tested PNG, not working at also.
<img width="1642" alt="CleanShot 2022-07-11 at 23 01 11@2x" src="https://user-images.githubusercontent.com/49930785/178294974-e3fc993c-7ba4-4df7-89ca-ffa7c6f588b3.png">

**Comment by edluffy** [comment]
Can you try the latest commit? I have made a few changes which includes encoding and sending only the image path to the terminal instead of the entire image contents - which is a _considerable_ performance increase and should mean that masses of base64 data isn't dumped into the terminal like that.

**Comment by winkee01** [comment]
I tried the latest commit, but still nothing was shown.
<img width="1535" alt="CleanShot 2022-07-11 at 23 09 13@2x" src="https://user-images.githubusercontent.com/49930785/178296823-b7fcb870-dc0b-45b2-9e69-252e456cf9ed.png">

this is my test image `laptop.png`
![image](https://user-images.githubusercontent.com/49930785/178297029-486e11e9-a035-4616-bc3a-5f4df010d15a.png)

**Comment by edluffy** [comment]
It works fine for me. What OS are you using and what version of Kitty do you have installed?
![lp](https://user-images.githubusercontent.com/28115337/178300545-9073cf7a-0251-4ca6-ab86-88e96c1e0777.png)

**Comment by winkee01** [comment]
I am using macOS Monterey, and I just installed kitty on my machine (never used it before), so I guess it's the latest version 0.25.2.

So my question is: except for your minimal settings, did I miss any other configs?
